language: go

go:
  - "1.11"

branches:
  only:
    - master

notification:
  email:
    recipients:
      - dev.moreal@gmail.com

    on_success: change
    on_failure: always

before_install:
  - cd dirty_go_study
  - ls

install:
  - echo "do nothing"

script:
  - go build .