language: go

go:
  - "1.11"

branches:
  only:
    - master

notification:
  email:
    recipients:
      - dev.moreal@gmail.com

    on_success: change
    on_failure: always

before_script:
  - go vet ./...
  
script: go test .